---
blank_issues_enabled: false
contact_links:
  - name: Exam DP-420 Microsoft Azure Cosmos DB Developer Crash Course Community Support
    url: https://github.com/timothywarner/dp420/discussions
    about: Please ask and answer questions here.
